#                       NUMPY

# Creating Array

In [15]:
import numpy as np


In [16]:
my_list1 = [1,2,3,4,5]# created list

In [17]:
my_array1 =np.array(my_list1)#make an array one dimensional

In [18]:
my_array1


array([1, 2, 3, 4, 5])

In [19]:
my_list2 = [12,23,33,43,53]

In [20]:
my_list3=[my_list1,my_list2]#two dimensional array

In [25]:
my_array2=np.array(my_list3)#creating two dimensional array

In [26]:
my_array2

array([[ 1,  2,  3,  4,  5],
       [12, 23, 33, 43, 53]])

In [27]:
my_array2.shape# shape of  array 2 rows ,5column

(2, 5)

In [28]:
my_array2.dtype# get the datatype

dtype('int32')

In [29]:
np.zeros(10)#get 10 zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
check_array_type=np.zeros(10)#check datatype of zeros

In [32]:
check_array_type.dtype

dtype('float64')

In [33]:
np.ones([7,7])#multidimensional array

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [41]:
np.empty(7) # create empty array

array([1., 1., 1., 1., 1., 1., 1.])

In [39]:
np.eye(7)#identity matrix 7*7 array of 0 with 1 on diagonal

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [42]:
np.arange(7)# get range

array([0, 1, 2, 3, 4, 5, 6])

In [40]:
np.arange(6,40,2)

array([ 6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])