In [5]:
import numpy as np
                        # two dimensional arrays
m1 = np.array([[16,44,72],[29,52,89]])
m2 = np.array([[18,49],[22,59],[32,69]])
m3 = np.dot(m1,m2) 
print(m3) 

[[ 3560  8348]
 [ 4514 10630]]


In [6]:
m1 = ([14, 60, 54],[37 ,40, 8],[22, 12, 39]) 
m2 = ([33, 45, 60],[56, 63, 76],[69,56, 76]) 
m3 = np.dot(m1,m2) 
print(m3) 

[[7548 7434 9504]
 [4013 4633 5868]
 [4089 3930 5196]]


In [4]:
import numpy as np

A = [[77, 89],
      [68, 39]]
      
B = [[76, 23],
      [95, 27]]

print(np.dot(A,B))

print("************")

print(np.dot(B,A))

[[14307  4174]
 [ 8873  2617]]
************
[[7416 7661]
 [9151 9508]]


In [15]:
import numpy as np

A = [[35, 70],
      [50, 65]]
 
B = [35, 72]
 
print(np.matmul(A,B))

[6265 6430]


In [10]:
import numpy as np

A = np.array([[61, 43, 5, 77, 9], [27, 49, 6, 87, 10]])

B = np.array([[41, 42, 73, 4, 5], [85, 47, 73, 28, 1]])

print(np.multiply(A,B))

[[2501 1806  365  308   45]
 [2295 2303  438 2436   10]]
