# Slicing & Indexing

In [1]:
import numpy as np

In [20]:
arr=np.arange(0,16)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [22]:
arr[10] #call the values of 10 using index

10

In [23]:
arr[0:8]# 0 t0 8

array([0, 1, 2, 3, 4, 5, 6, 7])

In [24]:
arr[0:10]=88#set allthe values of index 0 to 10 to set value as 88

In [25]:
arr


array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 10, 11, 12, 13, 14, 15])

In [26]:
arr[1]=20#set the value of 1'st index as 20

In [27]:
arr

array([88, 20, 88, 88, 88, 88, 88, 88, 88, 88, 10, 11, 12, 13, 14, 15])

In [28]:
aar=arr[:]

In [33]:
arr_r=np.array(([2,4,6],[3,7,8],[3,5,7]))# make anarray three dimentional
arr_r

array([[2, 4, 6],
       [3, 7, 8],
       [3, 5, 7]])

In [39]:
arr_r[0],arr_r[1],arr_r[2]

(array([2, 4, 6]), array([3, 7, 8]), array([3, 5, 7]))

In [40]:
arr_r[1][2]

8

In [45]:
arr_r

array([[2, 4, 6],
       [3, 7, 8],
       [3, 5, 7]])