Array function(Universal)

In [2]:
import numpy as np

In [3]:
arr=np.arange(15)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739])

In [6]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06])

In [10]:
S=np.random.randn(20)

In [11]:
S

array([ 1.12832187,  2.51481926, -2.11028472, -1.24718548,  0.27639505,
        0.53825631, -0.72150328,  1.54759723,  0.00921579, -1.92013576,
       -1.02989525,  1.64813348, -0.74481944,  0.577187  ,  0.37178551,
        0.46133678, -0.90037333,  1.14598464, -1.18010922,  0.49025578])

In [12]:
N=np.random.randn(20)

In [13]:
N

array([-1.08168606e+00, -4.21216944e-01,  1.51070200e+00,  1.17493285e+00,
        2.22912116e-01, -1.66537244e-02, -6.02343501e-01,  1.03760486e+00,
        6.89273344e-02, -5.37147459e-01, -6.69109574e-01, -3.54939167e-01,
       -8.21300951e-01,  1.39920060e-03,  2.69993146e-01,  1.01127293e-01,
       -1.34309128e+00, -4.84268541e-02,  1.43722773e+00,  6.94445125e-01])

In [14]:
np.add(N,S)

array([ 0.04663581,  2.09360231, -0.59958272, -0.07225263,  0.49930716,
        0.52160259, -1.32384678,  2.5852021 ,  0.07814313, -2.45728322,
       -1.69900482,  1.29319431, -1.5661204 ,  0.5785862 ,  0.64177865,
        0.56246407, -2.2434646 ,  1.09755779,  0.25711851,  1.1847009 ])

In [15]:
np.maximum(N,S)

array([ 1.12832187,  2.51481926,  1.510702  ,  1.17493285,  0.27639505,
        0.53825631, -0.6023435 ,  1.54759723,  0.06892733, -0.53714746,
       -0.66910957,  1.64813348, -0.74481944,  0.577187  ,  0.37178551,
        0.46133678, -0.90037333,  1.14598464,  1.43722773,  0.69444513])