In [ ]:
import numpy as np

In [9]:
arr = np.array([[1, 2, 3, 4],[8,9,10,11]])#make an array


In [15]:
arr

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [21]:
arr * arr   #multiply 

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [22]:
arr.shape # no of rows & column

(2, 4)

In [23]:
arr-arr  #subsract

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
1/arr#divide

array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [25]:
arr **3# exponential operation(power)

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [26]:
arr*2

array([[ 2,  4,  6,  8],
       [16, 18, 20, 22]])

In [27]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.82842712, 3.        , 3.16227766, 3.31662479]])

In [28]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [29]:
np.abs(arr)

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [30]:
np.ceil(arr)

array([[ 1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.]])

In [31]:
np.floor(arr)

array([[ 1.,  2.,  3.,  4.],
       [ 8.,  9., 10., 11.]])

In [32]:
np.round(arr)

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [34]:
np.power(arr,3)#power

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)

In [35]:
np.sin(arr)

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])